version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: behdasht-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - SERVICE_FQDN_behdasht_3000
      - KAVENEGAR_API_KEY: ${KAVENEGAR_API_KEY}
      - DB_CONNECTION: sqlite
      - DB_DATABASE: /var/www/db.sqlite
      - APP_KEY: ${APP_KEY}
    volumes:
      - ./db.sqlite:/var/www/db.sqlite

    networks:
      - behdasht-network
    command: php /var/www/artisan serve --host=0.0.0.0

networks:
  behdasht-network:
    driver: bridge 