version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: behdasht-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - SERVICE_FQDN_behdasht_3000
      - CACHE_DRIVER: file
      - SESSION_DRIVER: file
      - QUEUE_CONNECTION: sync
    volumes:
      - ./storage:/var/www/storage
      - ./db.sqlite:/var/www/db.sqlite
    networks:
      - behdasht-network
    command: php /var/www/artisan serve --host=0.0.0.0

networks:
  behdasht-network:
    driver: bridge 