version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: behdasht-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./db.sqlite:/var/www/db.sqlite
    ports:
      - "8000:8000"
    networks:
      - behdasht-network
    command: php artisan serve

networks:
  behdasht-network:
    driver: bridge 