version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: behdasht-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    networks:
      - behdasht-network
    command: php artisan serve --host=0.0.0.0

networks:
  behdasht-network:
    driver: bridge 